source 'https://cdn.cocoapods.org/'
platform :ios, '8.0'
use_frameworks!

target 'PodAsset_Example' do
  pod 'PodAsset', :path => '../'
  pod 'TestPod', :path => '../DevelopmentPods/TestPod'
  pod 'FrameworkPod', :path => '../DevelopmentPods/FrameworkPod'
end

target 'PodAsset_Tests' do
  pod 'PodAsset', :path => '../'
  pod 'TestPod', :path => '../DevelopmentPods/TestPod'
  pod 'FrameworkPod', :path => '../DevelopmentPods/FrameworkPod'
  pod 'Kiwi'
end
